// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoHead.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msg {

  /// <summary>Holder for reflection information generated from ProtoHead.proto</summary>
  public static partial class ProtoHeadReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoHead.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoHeadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0hlYWQucHJvdG8SA21zZyq1BwoPRU5ldHdvcmtNZXNzYWdlEhMK",
            "D0tFRVBfQUxJVkVfU1lOQxAAEhAKDFJFR0lTVEVSX1JFURABEhAKDFJFR0lT",
            "VEVSX1JTUBACEg0KCUxPR0lOX1JFURADEg0KCUxPR0lOX1JTUBAEEhgKFFBF",
            "UlNPTkFMU0VUVElOR1NfUkVREAUSGAoUUEVSU09OQUxTRVRUSU5HU19SU1AQ",
            "BhIUChBHRVRfVVNFUklORk9fUkVREAcSFAoQR0VUX1VTRVJJTkZPX1JTUBAI",
            "EhIKDkFERF9GUklFTkRfUkVREAkSEgoOQUREX0ZSSUVORF9SU1AQChIVChFE",
            "RUxFVEVfRlJJRU5EX1JFURALEhUKEURFTEVURV9GUklFTkRfUlNQEAwSEAoM",
            "T0ZGTElORV9TWU5DEA0SDgoKTE9HT1VUX1JFURAOEg4KCkxPR09VVF9SU1AQ",
            "DxIYChRHRVRfUEVSU09OQUxJTkZPX1JFURAQEhgKFEdFVF9QRVJTT05BTElO",
            "Rk9fUlNQEBESFgoSQ0hBTkdFX0ZSSUVORF9TWU5DEBISEQoNU0VORF9DSEFU",
            "X1JFURATEhEKDVNFTkRfQ0hBVF9SU1AQFBIVChFSRUNFSVZFX0NIQVRfU1lO",
            "QxAVEhkKFUNSRUFURV9HUk9VUF9DSEFUX1JFURAWEhkKFUNSRUFURV9HUk9V",
            "UF9DSEFUX1JTUBAXEhQKEENIQU5HRV9HUk9VUF9SRVEQGBIUChBDSEFOR0Vf",
            "R1JPVVBfUlNQEBkSFQoRQ0hBTkdFX0dST1VQX1NZTkMQGhIWChJHRVRfR1JP",
            "VVBfSU5GT19SRVEQGxIWChJHRVRfR1JPVVBfSU5GT19SU1AQHBIWChJFTlRF",
            "Ul9MSVZFSEFMTF9SRVEQZBIWChJFTlRFUl9MSVZFSEFMTF9SU1AQZRIVChFF",
            "WElUX0xJVkVIQUxMX1JFURBmEhUKEUVYSVRfTElWRUhBTExfUlNQEGcSFgoS",
            "RU5URVJfTElWRVJPT01fUkVREGgSFgoSRU5URVJfTElWRVJPT01fUlNQEGkS",
            "FwoTRU5URVJfTElWRVJPT01fU1lOQxBqEhUKEUVYSVRfTElWRVJPT01fUkVR",
            "EGsSFQoRRVhJVF9MSVZFUk9PTV9SU1AQbBIWChJFWElUX0xJVkVST09NX1NZ",
            "TkMQbRIVChFNT1ZFX1BPU0lUSU9OX1JFURBuEhUKEU1PVkVfUE9TSVRJT05f",
            "UlNQEG8SFgoSTU9WRV9QT1NJVElPTl9TWU5DEHBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msg.ENetworkMessage), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ENetworkMessage {
    [pbr::OriginalName("KEEP_ALIVE_SYNC")] KeepAliveSync = 0,
    [pbr::OriginalName("REGISTER_REQ")] RegisterReq = 1,
    [pbr::OriginalName("REGISTER_RSP")] RegisterRsp = 2,
    [pbr::OriginalName("LOGIN_REQ")] LoginReq = 3,
    [pbr::OriginalName("LOGIN_RSP")] LoginRsp = 4,
    [pbr::OriginalName("PERSONALSETTINGS_REQ")] PersonalsettingsReq = 5,
    [pbr::OriginalName("PERSONALSETTINGS_RSP")] PersonalsettingsRsp = 6,
    [pbr::OriginalName("GET_USERINFO_REQ")] GetUserinfoReq = 7,
    [pbr::OriginalName("GET_USERINFO_RSP")] GetUserinfoRsp = 8,
    [pbr::OriginalName("ADD_FRIEND_REQ")] AddFriendReq = 9,
    [pbr::OriginalName("ADD_FRIEND_RSP")] AddFriendRsp = 10,
    [pbr::OriginalName("DELETE_FRIEND_REQ")] DeleteFriendReq = 11,
    [pbr::OriginalName("DELETE_FRIEND_RSP")] DeleteFriendRsp = 12,
    [pbr::OriginalName("OFFLINE_SYNC")] OfflineSync = 13,
    [pbr::OriginalName("LOGOUT_REQ")] LogoutReq = 14,
    [pbr::OriginalName("LOGOUT_RSP")] LogoutRsp = 15,
    [pbr::OriginalName("GET_PERSONALINFO_REQ")] GetPersonalinfoReq = 16,
    [pbr::OriginalName("GET_PERSONALINFO_RSP")] GetPersonalinfoRsp = 17,
    [pbr::OriginalName("CHANGE_FRIEND_SYNC")] ChangeFriendSync = 18,
    [pbr::OriginalName("SEND_CHAT_REQ")] SendChatReq = 19,
    [pbr::OriginalName("SEND_CHAT_RSP")] SendChatRsp = 20,
    [pbr::OriginalName("RECEIVE_CHAT_SYNC")] ReceiveChatSync = 21,
    [pbr::OriginalName("CREATE_GROUP_CHAT_REQ")] CreateGroupChatReq = 22,
    [pbr::OriginalName("CREATE_GROUP_CHAT_RSP")] CreateGroupChatRsp = 23,
    [pbr::OriginalName("CHANGE_GROUP_REQ")] ChangeGroupReq = 24,
    [pbr::OriginalName("CHANGE_GROUP_RSP")] ChangeGroupRsp = 25,
    [pbr::OriginalName("CHANGE_GROUP_SYNC")] ChangeGroupSync = 26,
    [pbr::OriginalName("GET_GROUP_INFO_REQ")] GetGroupInfoReq = 27,
    [pbr::OriginalName("GET_GROUP_INFO_RSP")] GetGroupInfoRsp = 28,
    /// <summary>
    ///进入大厅请求，返回
    /// </summary>
    [pbr::OriginalName("ENTER_LIVEHALL_REQ")] EnterLivehallReq = 100,
    [pbr::OriginalName("ENTER_LIVEHALL_RSP")] EnterLivehallRsp = 101,
    /// <summary>
    ///退出大厅请求，返回
    /// </summary>
    [pbr::OriginalName("EXIT_LIVEHALL_REQ")] ExitLivehallReq = 102,
    [pbr::OriginalName("EXIT_LIVEHALL_RSP")] ExitLivehallRsp = 103,
    /// <summary>
    ///进入一个直播房间请求，返回，同步
    /// </summary>
    [pbr::OriginalName("ENTER_LIVEROOM_REQ")] EnterLiveroomReq = 104,
    [pbr::OriginalName("ENTER_LIVEROOM_RSP")] EnterLiveroomRsp = 105,
    [pbr::OriginalName("ENTER_LIVEROOM_SYNC")] EnterLiveroomSync = 106,
    /// <summary>
    ///退出一个直播房间请求，返回，同步
    /// </summary>
    [pbr::OriginalName("EXIT_LIVEROOM_REQ")] ExitLiveroomReq = 107,
    [pbr::OriginalName("EXIT_LIVEROOM_RSP")] ExitLiveroomRsp = 108,
    [pbr::OriginalName("EXIT_LIVEROOM_SYNC")] ExitLiveroomSync = 109,
    /// <summary>
    ///移动位置请求，返回，同步
    /// </summary>
    [pbr::OriginalName("MOVE_POSITION_REQ")] MovePositionReq = 110,
    [pbr::OriginalName("MOVE_POSITION_RSP")] MovePositionRsp = 111,
    [pbr::OriginalName("MOVE_POSITION_SYNC")] MovePositionSync = 112,
  }

  #endregion

}

#endregion Designer generated code
